# Changes here will be overwritten by Copier
_commit: v0.2.4
_src_path: gh:reservoir-data/singer-tap-copier-template
author_email: edgarrmondragon@hey.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: Etc/UTC
python_main_version: '3.12'
repository_name: tap-honeybadger
repository_namespace: reservoir-data
repository_provider: github.com
repository_visibility: private
tap_auth_method: Basic Auth
tap_id: tap-honeybadger
tap_package_command_line_name: tap-honeybadger
tap_package_distribution_name: tap-honeybadger
tap_package_import_name: tap_honeybadger
tap_source_description: Application monitoring that helps developers get it done.
tap_source_id: Honeybadger
tap_source_name: Honeybadger
tap_stream_type: REST
vscode_files: true
